sudo: required
services:
  - docker

before_install:
  - docker build -t csilva/docker-react -f Dockerfile.dev .


script:
  - docker run csilva/docker-react npm run test -- --coverage
  

deploy:
  provider: elasticbeansstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-323216669271"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
